NVIDIA/bionemo-framework

sub-packages/bionemo-core/src/bionemo/core/data/multi_epoch_dataset.py, sub-packages/bionemo-core/src/bionemo/core/data/permute.py, sub-packages/bionemo-core/tests/bionemo/pytorch/data/test_multi_epoch_dataset.py, sub-packages/bionemo-core/tests/bionemo/pytorch/data/test_permute.py, sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_model.py
Uses a new algorithm for permuting datasets in `MultiEpochDataset`. The memory consumption should now be O(n_epochs) since we just store the random seeds.
=> optimize multi_epoch_dataset for constant memory and space usage

sub-packages/bionemo-esm2/tests/bionemo/esm2/conftest.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/model/test_stop_and_go.py, sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_stop_and_go.py, sub-packages/bionemo-testing/src/bionemo/testing/data/esm2.py, sub-packages/bionemo-testing/src/bionemo/testing/harnesses/mode.py, sub-packages/bionemo-testing/src/bionemo/testing/harnesses/stop_and_go.py, sub-packages/bionemo-testing/src/bionemo/testing/testing_callbacks.py, sub-packages/bionemo-testing/src/bionemo/testing/torch.py
Refactors the stop and go test suite so that most checks assert that the input/output of an interrupted model run match those trained continuously.
=> Refactor stop and go test suite

docs/docs/user-guide/examples/bionemo-esm2/pretrain.md
To address comments on VDR feedback.
https://docs.google.com/document/d/1JnXzuuA_0ovmN0KcO4sGCRNu86KGClaYd4HY0rQgiYM/edit?tab=t.0
=> Improve ESM2 pretraining VDR

sub-packages/bionemo-esm2/tests/bionemo/esm2/data/test_datamodule.py, sub-packages/bionemo-llm/src/bionemo/llm/utils/datamodule_utils.py
Removes the tensor_dict_hash function in favor of a more explicit equality test.
=> Remove tensor_dict_hash in favor of recursive approx_equal

scripts/singlecell/geneformer/train.py, sub-packages/bionemo-geneformer/src/bionemo/geneformer/api.py, sub-packages/bionemo-geneformer/src/bionemo/geneformer/data/singlecell/datamodule.py, sub-packages/bionemo-geneformer/src/bionemo/geneformer/data/singlecell/dataset.py, sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_model.py, sub-packages/bionemo-llm/src/bionemo/llm/model/biobert/model.py
Moves the remaining changes from #312 into a fresh PR
=> Move Geneformer dataset to MultiEpochDatasetResampler

sub-packages/bionemo-scdl/pyproject.toml, sub-packages/bionemo-scdl/src/bionemo/scdl/io/single_cell_memmap_dataset.py
=> small bug fix

.github/workflows/blossom-ci.yml
Reverts NVIDIA/bionemo-framework#431
=> Revert "re-enable merge groups to trigger blossom-ci"

docs/bionemo/models/dsmbind.md
_Update the title for DSMBind doc so that the link in documentation can work_
=> Update the title for DSMBind doc

README.md
Modified README to include documentation and release info
Added details on how to download the container and where to find documentation, user guides, API references and trouble shooting information
Not Applicable as this is just a modification to the README
Not Applicable as this is just a modification to the README
=> Add documentation and release info to README

internal/scripts/build_dev_image.sh
=> Cache dev build from our nightly public container

docs/docs/user-guide/appendix/releasenotes-fw.md
- Add release notes for BioNeMo Framework v2.2.
- New Features
- @sveccham GNN Compose
- @gagank1 GH200 Support
- Improvements
- @polinabinder1 @savitha-eng SCDL Speed-Up
- @pstjohn @farhadrgh ESM2 Refactor + Fixes
- Not relevant.
- Needs review.
=> [v2.2] Publish release notes for BioNeMo FW v2.2.

docs/mkdocs.yml
Updates nightly docker tag to match NGC registry
=> Update nightly Docker image tag

sub-packages/bionemo-esm2/src/bionemo/esm2/model/finetune/datamodule.py
Fix typo in label key.
Check for loading labels should use "labels" instead of "label". 
Fixed the typo
n/a
no new tests
=> Fix csv dataset

ci/scripts/run_pytest.sh
Attempt to run pytests in all submodules even if individual packages fail.
=> Run all pytests even if submodules fail

requirements-test.txt
Pins the version of cdifflib to avoid a build failure. See mduggan/cdifflib#13
Configure CI behavior by checking relevant boxes below. This will automatically apply labels.
> [!NOTE]
```python
```
=> pin cdifflib version

docs/docs/user-guide/background/megatron_datasets.md, docs/docs/user-guide/getting-started/index.md
Thanks to Savitha for pointing out this bit of the docs that's no longer relevant. We have a new algorithm here that makes the MultiEpochDataset also O(1)
=> Remove outdated note on very large datasets in MultiEpochDataset

ci/benchmarks/partial-conv/esm2_pretrain.yaml
Configure CI behavior by checking relevant boxes below. This will automatically apply labels.
> [!NOTE]
```python
```
=> fix esm2_pretrain.yaml

.github/workflows/unit-tests.yml
Adds some additional comments to the unit-test workflow file
> [!NOTE]
```python
```
=> add comments to the unit-test.yaml file

CODEOWNERS
Adds ESM2 to the CODEOWNERS section
- []  Refactor
> [!NOTE]
```python
```
=> Adds bionemno-esm2 section to CODEOWNERS

sub-packages/bionemo-llm/src/bionemo/llm/run/config_models.py, sub-packages/bionemo-llm/src/bionemo/llm/train.py
Fix CI by dropping PerplexityCallback in pydantic api
- [x ]  Bug fix (non-breaking change which fixes an issue)
```bash
pytest sub-packages/bionemo-esm2/tests/bionemo/esm2/scripts/test_pydantic_train.py::test_pretrain_pydantic_cli
```
Related to https://github.com/NVIDIA/bionemo-framework/commit/e5533890c2299657cdcb8a1e891dd152c9c5378a
=> remove PerplexityCallback in pydantic api

docs/docs/user-guide/appendix/releasenotes-fw.md
=> 2.3 (25.01) release notes

sub-packages/bionemo-esm2/src/bionemo/esm2/scripts/train_esm2.py
Add timing callback to log train step time in second
=> add timing callback

.github/workflows/unit-tests.yml, ci/scripts/run_pytest.sh, pyproject.toml
Adds duration logging for slow and notebook steps in the github CI
=> add options for pytest duration logging

setup/requirements-cve.txt, setup/requirements.txt
Fixing vulnerabilities found by CVE for `bionemo1`
usr/local/lib/python3.10/dist-packages/urllib3 (fixed in:   1.26.17)(https://github.com/advisories/GHSA-v845-jxx5-vc9f)
/usr/local/lib/python3.10/dist-packages/tornado (fixed in:  6.4.2)(https://github.com/advisories/GHSA-8w49-h785-mj3c)
- [INCLUDE_SLOW_TESTS](https://github.com/NVIDIA/bionemo-framework/blob/main/docs/docs/u …
=> fix CVE - bionemo1

README.md
Fixes #653 by updating the container link the main README
=> Fix nightly container link in README

README.md
Add announcement note on readme
=> add announcement README.md

.pre-commit-config.yaml, sub-packages/bionemo-esm2/src/bionemo/esm2/model/finetune/datamodule.py, sub-packages/bionemo-esm2/src/bionemo/esm2/model/finetune/dataset.py, sub-packages/bionemo-esm2/src/bionemo/esm2/scripts/finetune_esm2.py
=> Adjust ESM2 fine-tuning to allow NVFlare usecases

sub-packages/bionemo-evo2/src/bionemo/evo2/utils/__init__.py, sub-packages/bionemo-evo2/src/bionemo/evo2/utils/checkpoint/__init__.py
Add license header to new files causing CI failure.
=> Add new license to new files (failing ci)

sub-packages/bionemo-evo2/src/bionemo/evo2/run/train.py, sub-packages/bionemo-evo2/tests/bionemo/evo2/run/test_train.py
Slightly refactoring train script for evo2 to better handle unit testing and a bug fix
> [!NOTE]
> By default, the notebooks validation tests are skipped unless …
=> evo2 train unit test

Dockerfile, requirements-cve.txt
Addressing CVE vulnerability https://github.com/advisories/GHSA-g4r7-86gm-pgqc
It is introduced in `requirements_eval.txt` (NeMo) by `lm_eval` package, which depends on `sqlitedict` (all versions have critical vulnerability).
- [INCLUDE_SLOW_TESTS](https://github.com/NVIDIA/bionemo-framework/blob/main/docs/docs/user-guide/contributing/contributing.md#include_slow_tests) - …
=> cve vulnerability on main

sub-packages/bionemo-core/src/bionemo/core/data/resources/evo2.yaml, sub-packages/bionemo-evo2/src/bionemo/evo2/utils/checkpoint/convert_to_nemo.py
1b checkpoint is not capable of doing inference with bf16 in a biologically relevant way. This fine-tuned checkpoint fixes that.
=> Adding bf16 fine-tuned variant of evo2 1b checkpoint

.github/workflows/unit-tests.yml
Disables slow-running tests in the merge queue step
=> Disable notebook and slow tests from running in merge queue

sub-packages/bionemo-evo2/examples/fine-tuning-tutorial.ipynb, sub-packages/bionemo-evo2/examples/zeroshot_brca1.ipynb
Now that our notebooks are merged in `main`, I've recreated the brev.dev launchables to build from these notebooks, and update the badges accordingly.
=> Update brev.dev badges to launchable built off main branch

ci/benchmarks/partial-conv/evo2_pretrain.yaml
Updating max number of steps to 6900 for the script to execute within max time limit - 4h
> [!NOTE]
> By default, the notebooks validation tests are skipped unless …
=> update evo2 partial conv max steps

docs/docs/user-guide/appendix/releasenotes-fw.md
Adding release notes for v2.5 release: https://github.com/NVIDIA/bionemo-framework/releases/tag/v2.5
> [!NOTE]
> By default, the notebooks validation tests are …
=> adding v2.5 release notes

README.md
Remove outdated announcement from README.
=> Remove Evo2 PR announcement now that everything is merged

.github/workflows/unit-tests.yml
I'm not sure the existing cache-from command is working correctly, let's try this config
=> switch cache-from flags

.github/workflows/unit-tests.yml, docs/conftest.py
Skipping execution of this notebook in GitHub CI due execution error
`pytest -v --nbval-lax -p no:python --ignore="docs/docs/user-guide/examples/bionemo-geneformer/geneformer_cellxgene_tutorial.ipynb" docs/ sub-packages/`
Issue: https://github.com/NVIDIA/bionemo-framework/issues/778
- [INCLUDE_SLOW_TESTS](https://github.com/NVIDIA/bionemo-framework/blob/main/docs/docs/user-g …
=> [hotfix] setting as "ignore" the failing notebook geneformer_cellxgene_tutorial.ipynb

sub-packages/bionemo-moco/environment/Instructions.md, sub-packages/bionemo-moco/environment/clone_bionemo_moco.sh, sub-packages/bionemo-moco/pyproject.toml, sub-packages/bionemo-moco/tests/bionemo/moco/interpolants/continuous_time/continuous/test_optimal_transport.py
Add script to clone bionemo-moco sub-package directly.
Also cleaned up dependencies in tests.
=> Add local clone script

sub-packages/bionemo-moco/README.md
=> Update README.md link

Dockerfile
- `pip install` Rapids SingleCell: https://rapids-singlecell.readthedocs.io/en/latest/Installation.html
```
$ ./internal/scripts/build_dev_image.sh
$ docker run -it --gpus=all --rm nvcr.io/nvidian/cvai_bnmo_trng/bionemo:dev-bionemo2-a643d8c073262a542c7b94cc39648173d87c1d8e
$ pip freeze | grep rapids-singlecell
rapids_singlecell==0.12.1
```
```python
import rapids_singlecell as rsc
```
=> [cye/rapids-sc-install] Add rapids_singlecell import to BioNeMo FW container image.

README.md, docs/docs/user-guide/index.md
Adds links to subscribe to NVIDIA biopharma mailing list 
> [!NOTE]
We use …
=> Biopharma mailing list docs addition.

Dockerfile
Bitsandbytes needs to be built from scratch for ARM (GH200) machines.
Overall, we need to add GH200 CI to pre-merge somehow -- TODO for later.
> [!NOTE]
> By …
=> Fix bitsandbytes issue on ARM

ci/benchmarks/partial-conv/esm2_pretrain.yaml
…ESM2 model
The PR will update the baseline for some performance metrics
- consumed_samples
- val_loss
- reduced_train_loss
- tflops_per_sec_per_gpu
These metrics can be used to validate the actual metrics from actual executions.
- [x ]  New feature (non-breaking change which adds functionality)
- [INCLUDE_SLOW_TESTS](https://github.com/NVIDIA/bionemo-framework/blob/main/doc …
=> Adding baseline metrics for benchmarking ESM2 model

docs/docs/models/geneformer.md, docs/docs/user-guide/appendix/releasenotes-fw.md
Release notes for v2.6
> [!NOTE]
We use …
=> Release notes v2.6

Dockerfile
Upgrade the Docker base image to 25.04
> [!NOTE]
We use …
=> upgrade pytorch to 25.04

Dockerfile
Pin the version of `scikit-misc` to `0.3.1` because newer versions require version of `numpy>=2.0` at build time. Since there are not pre-built wheels for `linux/arm64` this causes a conflict since `bionemo` is not compatible with `numpy>=2.0`. This version of `scikit-misc` does not require `numpy>=2.0` to be built.
- …
=> [BIONEMO-1831] Fix the version of scikit-misc to resolve dependency issue

docs/docs/index.md, docs/overrides/main.html
Fix broken links and add banner warning bas version
=> Fix broken links and add banner

sub-packages/bionemo-amplify/src/bionemo/amplify/train_amplify.py
Fix for https://nvidia.slack.com/archives/C04MP1Q7JBY/p1747737900430989; where the QA test plan fails on trying to load the full HF dataset with a mounted cache folder. This PR adds a flag to `use_sanity_dataset` to `train_amplify`; which loads a single train and test parquet shard (~300Mb total).
=> add flag for loading a sanity-sized dataset for AMPLIFY

requirements-cve.txt
Fixing CVE vunlerabilities:
https://github.com/advisories/GHSA-5rjg-fvgr-3xxf
https://github.com/advisories/GHSA-7cx3-6m66-7c5m
> [!NOTE]
> By default, the …
=> fixing vulnerabilities: setuptools and tornado

sub-packages/bionemo-evo2/tests/bionemo/evo2/test_evo2.py
The pytorch 25.04 has CUDA 12.9 installed:
```
Build cuda_12.9.r12.9/compiler.35813241_0
```
while pytorch 25.01 has 12.8
```
Cuda compilation tools, release 12.8, V12.8.61
Build cuda_12.8.r12.8/compiler.35404655_0
```
This seems to be causing numerical differences so that strict checking of tensor values fails.
Remove a strict tensor comparison that doesn't hold across CUDA version.
- [INCLUDE_NOTEBOOKS_TESTS](https://github.com/NVIDIA/bionemo-framework/blob/main/docs/docs/user-guide/contributing/contributing.md#include_notebooks_tests) - Execute notebook validation tests …
=> Remove strict comparison of tensors against golden values in evo2 test

Dockerfile
The current installation of `bitsandbytes` is not configured to use the CUDA backend. This is causing errors in the Evo2 jupyter notebook `zeroshot_brca1.ipynb`. This PR builds `bitsandbytes` with CUDA backend.
- [INCLUDE_SLOW_TESTS](https://github.com/NVIDIA/bionemo-framework/blob/main/docs/docs/user-guide/contributing/contributing.md#include_slow_tests) - Execute tests …
=> [BIONEMO-2042] Install 'bitsandbytes' with cuda backend

docs/overrides/main.html
=> Update Docs Banner for GitHub Pages-hosted Docs

docs/docs/main/about/releasenotes-fw.md
Add release notes for v2.6.2 (25.06)
> [!NOTE]
We use …
=> Add release notes for v2.6.2 (25.06)

requirements-cve.txt
Fixes HIGH PIL Vuln but bumping version
> [!NOTE]
We use …
=> Fix PIL CVE

Dockerfile, patches/te.patch, sub-packages/bionemo-evo2/tests/bionemo/evo2/run/test_train.py
Currently, there is a bug in TE which prevents in certain cases to resume from a saved checkpoint. This PR adds a patch to TE to fix this issue. Once TE is upgraded to a newer version with the fix, the patch should be removed.
- [INCLUDE_SLOW_TESTS](https://github.com/NVIDIA/bionemo-framework/blob/main/docs/docs/user-guide/contributing/contributing.md#include_slow_tests) - …
=> [BIONEMO-2334] Patch TE to fix Evo2 stop and go training

sub-packages/bionemo-evo2/examples/zeroshot_brca1.ipynb
update evo2 broken link in zero shot notebook
> [!NOTE]
We use …
=> update evo2 zero shot notebook

ci/benchmarks/partial-conv/evo2_pretrain.yaml, ci/benchmarks/perf/evo2_pretrain.yaml, sub-packages/bionemo-evo2/src/bionemo/evo2/run/train.py
> \[!NOTE\]
We use [copy-pr-bot](https://docs.gha-runners.nvidia.com/apps/copy-pr …
=> Add subquadratic-ops support

sub-packages/bionemo-evo2/README.md
Remove extra -- from pipeline parallel command in docs
=> remove extra -- from pipeline parallel command

.github/workflows/unit-tests-framework.yml
Make sure changed-files includes 3rdparty/ for bionemo-framework tests
=> checkout submodules in framework changed-actions
