sub-packages/bionemo-testing/pyproject.toml, sub-packages/bionemo-testing/src/bionemo/testing/data/load.py
Adds a new flag, --all, to bionemo_data_download. This will override the other flags and download every possible resource, data and model, using the user-supplied --source.
This PR also refactors the script so that the variables are referenced to explicitly, rather than using the opaque argument parsed result object (args), aiding in readability & maintainability.
=> Add --all flag for bionemo_data_download

internal/scripts/setup_env_file.sh
Fixes a bug in that references the wrong variable in `setup_env_file.sh`. It's `LOCAL_REPO_PATH` not `LOCAL_DATA_PATH`.
=> bugfix - wrong variable referenced

docs/docs/datasets/uniprot.md, docs/docs/models/esm2.md, docs/docs/user-guide/appendix/releasenotes-fw.md, docs/docs/user-guide/examples/bionemo-esm2/finetune.md, docs/docs/user-guide/examples/bionemo-esm2/pretrain.md, docs/docs/user-guide/getting-started/development.md, sub-packages/bionemo-testing/src/bionemo/testing/data/README.md
Changes "ESM2" to "ESM-2" in markdown files
=> change ESM2 to ESM-2 in written docs

Dockerfile, sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_stop_and_go.py
Looks like for some reason, the output tensors are not consistent between the interrupted and continuous training runs without `NVTE_FUSED_ATTN=1 NVTE_FLASH_ATTN=0` set in the release container. These are set in the development container though, so we should keep these consistent.
Possibly the model isn't as deterministic without these set?
=> Export FUSED_ATTN in release container and fix geneformer stop and go

sub-packages/bionemo-esm2/tests/bionemo/esm2/model/test_stop_and_go.py, sub-packages/bionemo-testing/src/bionemo/testing/harnesses/stop_and_go.py, sub-packages/bionemo-testing/src/bionemo/testing/torch.py, sub-packages/bionemo-testing/tests/bionemo/testing/data/test_load.py
The mock dataset previously used was probably too small to possibly catch real issues in checkpoint resumption. Also adjusts the absolute tolerance for output tensors.
=> move esm2 stop and go test to sanity dataset

sub-packages/bionemo-esm2/src/bionemo/esm2/model/finetune/infer.py
This is to address QA Bug https://nvbugspro.nvidia.com/bug/4946953
By changing the output of predict method from a `list` to `dict` by using `batch_collator`
=> [QA BUG] apply batch_collator to predict results

docs/bionemo/access-startup.md
This command updates the command to automatically pull the latest BioNeMo1 tag. Addresses internal bug 4943423.
=> Update command to pull latest BioNeMo1 tag

sub-packages/bionemo-core/src/bionemo/core/data/load.py
Pooch automatically calculates a filename for downloads that is a function of the hash and the URL, but we want to ensure that downloads from NGC and PBSS have identical local filenames so that their cache is shared, and the URLs for both resources don't typically match.
Here we set the fname parameter manually so that we don't download duplicate objects from ngc and pbss
=> add fname parameter for pooch downloads

Dockerfile, docs/docs/user-guide/examples/bionemo-esm2/pretrain.md, scripts/gpt-pretrain.py, sub-packages/bionemo-esm2/src/bionemo/esm2/model/attention.py, sub-packages/bionemo-esm2/src/bionemo/esm2/model/finetune/train.py, sub-packages/bionemo-esm2/src/bionemo/esm2/model/model.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/data/test_tokenizer.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/model/finetune/test_finetune.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/model/test_stop_and_go.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/scripts/test_train_esm2.py, sub-packages/bionemo-example_model/src/bionemo/example_model/lightning/lightning_basic.py, sub-packages/bionemo-example_model/src/bionemo/example_model/training_scripts/finetune_mnist.py, sub-packages/bionemo-example_model/tests/bionemo/example_model/lightning/test_lightning_basic.py, sub-packages/bionemo-geneformer/src/bionemo/geneformer/scripts/train_geneformer.py, sub-packages/bionemo-geneformer/tests/bionemo/geneformer/scripts/test_train_geneformer.py, sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_model.py, sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_stop_and_go.py, sub-packages/bionemo-llm/src/bionemo/llm/model/biobert/model.py, sub-packages/bionemo-llm/src/bionemo/llm/utils/weight_utils.py, sub-packages/bionemo-llm/tests/bionemo/llm/test_lightning.py, sub-packages/bionemo-llm/tests/bionemo/llm/utils/test_iomixin_utils.py, sub-packages/bionemo-testing/src/bionemo/testing/harnesses/stop_and_go.py, sub-packages/bionemo-testing/src/bionemo/testing/testing_callbacks.py
Updates us to TOT NeMo and Megatron, and bumps the transformer engine version to 1.11.
Includes a number of fixes we need to make to be compatible with these newer versions, including changes to IOMixin
Branches off of #302.
Includes the fix from NeMo for validation batches after restart NVIDIA/NeMo#11029
=> Update NeMo and Megatron to TOT

.github/workflows/blossom-ci.yml
I'm hoping this doesn't brick our existing blossom workflow, but we'll need to quickly revert if it does. If we can get this merged to `main`, I'm hoping we can do the rest of our testing with merge groups with PRs to a seperate `main-merge-group` branch
=> re-enable merge groups to trigger blossom-ci

tests/test_download_sources.py
Disabling temporaty test which checks if NGC vs PBSS checksum match - nvidia/clara/openfold:finetuned_1.2 needs to have ngc no login perms
=> eliminate the need for NGC login - bionemo1

sub-packages/bionemo-core/tests/bionemo/core/data/test_load.py
Disabling test which checks if NGC client was logged
=> eliminate the need for NGC login - bionemo2

sub-packages/bionemo-core/tests/bionemo/core/data/test_load.py, sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_stop_and_go.py
This addresses a rare, random failure in the geneformer stop/go test @polinabinder1 observed [here](https://prod.blsm.nvidia.com/bionemo-external-bionemo-fw/job/test_pytest/826/console). This mirrors the setting we have now in main: https://github.com/NVIDIA/bionemo-framework/blob/main/sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_stop_and_go.py#L100
=> Update error prone stop/go atol to more stable setting

sub-packages/bionemo-esm2/tests/bionemo/esm2/model/finetune/test_finetune.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/model/test_model.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/model/test_stop_and_go.py
Should help to address errors like https://prod.blsm.nvidia.com/bionemo-external-bionemo-fw/job/test_pytest/838/console 
```14:14:12  E       RuntimeError: DataLoader worker (pid 8445) is killed by signal: Aborted.```
when we use too many resources on the CI machine
=> set num_workers to 1 for esm2 tests

docs/docs/user-guide/examples/bionemo-geneformer/geneformer-celltype-classification.ipynb
Marking this as skip because it's a change to a markdown cell.
=> Fix typos in geneformer benchmark description

docs/docs/user-guide/examples/bionemo-geneformer/geneformer-celltype-classification.ipynb, requirements-cve.txt, sub-packages/bionemo-scdl/src/bionemo/scdl/index/row_feature_index.py, sub-packages/bionemo-scdl/src/bionemo/scdl/io/single_cell_memmap_dataset.py, sub-packages/bionemo-scdl/tests/bionemo/scdl/index/test_row_feature_index.py, sub-packages/bionemo-scdl/tests/bionemo/scdl/io/test_single_cell_memmap_dataset.py, sub-packages/bionemo-size-aware-batching/src/bionemo/size_aware_batching/sampler.py, sub-packages/bionemo-size-aware-batching/tests/bionemo/size_aware_batching/test_sampler.py
In this PR we refactor the Geneformer `SingleCellDataset` class  to integrate the `SingleCellMemmapDataset`(SCDL). The goal of this is to streamline and increase readability of the dataset class. 
We make the following changes:
- Input Format: 
- The `SingleCellDataset` now assumes that the input path to the data is a directory formatted in the `SingleCellMemmap` format. 
-  The SingleCellModule now assumes that the train, val, and test input paths are to directories that are formatted in the `SingleCellMemmap` format 
- Get Item:
- `_get_item()` now leverages the get_row function from SCDL (so we eliminate the need to store and parse information in metadata.json)
- Error Handling for Genes not in the Tokenizer Vocabulary:
- We add an optional parameter to SingleCellDataset and …
=> Fully Integrate SCDL into Geneformer

sub-packages/bionemo-esm2/src/bionemo/esm2/model/finetune/train.py
This allows the checkpoint to be optionally downloaded from PBSS for QA testing.
This is a temporary solution to unblock QA - this example will be deprecated in the next release
=> [QA Bug] Remove NGC dependency 

ci/scripts/run_pytest.sh
Corrects the `source` field for the coverage report, prints out which lines are missed.
=> change source for coverage report

docs/docs/user-guide/getting-started/initialization-guide.md
Fix: Remove problematic quotes from startup command
This PR fixes an issue where the docker run command for BioNeMo 2 failed due to incorrect quoting of the JupyterLab startup command. The fix removes the quotes around the command.
=> Remove quotes for Jupyter command on startup in init guide

sub-packages/bionemo-esm2/src/bionemo/esm2/data/datamodule.py, sub-packages/bionemo-esm2/src/bionemo/esm2/model/finetune/datamodule.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/data/test_datamodule.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/scripts/test_train_esm2.py, sub-packages/bionemo-geneformer/src/bionemo/geneformer/data/singlecell/datamodule.py, sub-packages/bionemo-geneformer/tests/bionemo/geneformer/scripts/test_train_geneformer.py, sub-packages/bionemo-llm/src/bionemo/llm/utils/datamodule_utils.py
Allow `--limit-val-batches=0.` to disable validation. Same applies for testing in geneformer.
Previously validation dataset cannot be created when `limit_val_batches = 0.`. Now this is caught and the validation dataset is set to `None`. Same applies to test dataset.
Implemented in `sub-packages/bionemo-geneformer/tests/bionemo/esm2/scripts/test_train_esm2.py::test_val_dataloader_in_main_runs_with_limit_val_batches` and that in geneformer.
- The e2e test function only test whether it runs. It does not test whether validation is actually skipped.
- Currently there is no testing on finetuning.
=> Disable validation/test stages in ESM-2 and Geneformer

requirements-cve.txt, requirements-test.txt
- `wandb>=0.19.1`: `wandb` Path validation bug has been fixed [between 0.19.0 and 0.19.1](https://github.com/wandb/wandb/compare/v0.19.0...v0.19.1).
- Specifically, this commit / PR: [chore: allow pathlib.Path's for path-related Settings](https://github.com/wandb/wandb/commit/2f11cc702f80f42411b81b41f5d898ffbc00200a)
- CVE "Misuse of ServerConfig.PublicKeyCallback may cause authorization bypass in golang.org/x/crypto" is fixed in `0.19.1` as well. Two birds, one stone. (Was never a "true" vuln.)
- Resolves this NVBug for [CVE GHSA-v778-237x-gjrc](https://github.com/advisories/GHSA-v778-237x-gjrc): https://nvbugspro.nvidia.com/bug/5010582
- WandB PR: https://github.com/wandb/wandb/pull/9069#issuecomment-2540317234
- Slack Threads
- `Path` Validation Issue: …
=> [cye/wandb-fix] Fix WandB issue.

Dockerfile.arm, docs/docs/user-guide/appendix/releasenotes-fw.md, sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_model.py
Known issue on H100 (and GH200) with loading checkpoints. Also fixing CVE in ARM container
=> xFail known bad tests on H100 and fix CVEs

sub-packages/bionemo-esm2/src/bionemo/esm2/scripts/train_esm2.py, sub-packages/bionemo-llm/src/bionemo/llm/train.py
Update DDP config to speed up ESM-2 15B pretraining. Turn off `grad_reduce_in_fp32` in mixed precision plugin (default is True) to reduce memory consumption and `overlap_grad_reduce` and `average_in_collective` to improve performance.
Pause `overlap_param_gather=True` to wait for NeMo's fix.
=> Update ddp config to improve ESM-2 15B MFU

docs/requirements.txt
Pins mistune to fix a jupyter notebook build issue introduced in 3.1.0
lepture/mistune#403
=> add temporary mistune pin to fix docs build issue

Dockerfile, sub-packages/bionemo-fw/pyproject.toml
Attempts to update the base image to the most recent 24.12 release
=> update base image to 24.12

sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_model.py
Un-xfails a geneformer H100 test.
After base image upgrade to pytorch fw 24.12 (https://github.com/NVIDIA/bionemo-framework/pull/553) , H100 geneformer issue is fixed. 
```python
pytest ./sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_model.py::test_geneformer_nemo1_v_nemo2_inference_golden_values
```
=> Un-xfail geneformer on H100 test

.devcontainer/devcontainer.json, Dockerfile
The new ubuntu base container contains a couple of changes that breaks the (untested in CI) base container:
1. it now has a default 1000:1000 `ubuntu` user we can use, instead of creating a new bionemo user.
2. it uses python 3.12, which changes some of our copy paths.
=> update devcontainer for new ubuntu base image

sub-packages/bionemo-esm2/tests/bionemo/esm2/scripts/test_infer_esm2.py
Adding the load calls in the global namespace leads to these checkpoints being downloaded even when we don't use them. We really should call `load` as lazily as possible to avoid materializing data for tests we don't need.
=> don't eagerly download esm2 checkpoints

sub-packages/bionemo-esm2/src/bionemo/esm2/scripts/train_esm2.py
Turn on `overlap_param_gather` for an additional 4% MFU gain on 15B model pretraining
Dependent on NeMo2 fix on `overlap_param_gather` https://github.com/NVIDIA/NeMo/commit/bde672e75f1ac45ead08e2b977920a28eb81448e.
=> default to overlap_param_gather

.github/workflows/unit-tests.yml, ci/scripts/run_pytest.sh, sub-packages/bionemo-esm2/tests/bionemo/esm2/scripts/test_pydantic_train.py, sub-packages/bionemo-geneformer/tests/bionemo/geneformer/scripts/test_pydantic_train.py
These pydantic CLI tests are currently taking an inordinate amount of time to run. This PR adds support for using `pytest.mark.slow` to flag tests not to run during pre-merge testing, but will still be run during nightly tests.
Also adds some cleanup to the azure runner test suite to remove the docker container from the GPU runner since these are not ephemeral workers, and updates the cache mounting location for the container job to re-use downloads.
See https://nvidia.slack.com/archives/C074Z808N05/p1736460988702949
https://jirasw.nvidia.com/browse/BIONEMO-553
Configure CI behavior by checking relevant boxes below. This will automatically apply labels.
> [!NOTE]
```python
```
=> Add support for marking and skipping slow tests, temporarily mark pydantic tests as slow

requirements-test.txt
This reverts commit 2e90bf5872bef1987ac15b2619cc3a4196e77e53.
We don't need this anymore (assuming tests pass with the new version) thanks to quick action here: mduggan/cdifflib#13
Configure CI behavior by checking relevant boxes below. This will automatically apply labels.
> [!NOTE]
```python
```
=> Revert "pin cdifflib version (#593)"

.github/workflows/blossom-ci.yml
Adding myself to be able to run ci
=> add myself to ci

.github/workflows/unit-tests.yml
Trufflehog is currently failing on the main branch when we only run on diffs, since it ends up comparing the head of main against itself. This should allow us to check the entire main branch for secrets when it runs post-merge.
> [!NOTE]
```python
```
=> run trufflehog on entire main branch on push action

.devcontainer/devcontainer.json
Updates paths in the devcontainer config for the new ubuntu default user.
> [!NOTE]
```python
```
=> fix devcontainer paths in ubuntu 24

sub-packages/bionemo-esm2/src/bionemo/esm2/data/datamodule.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/data/test_datamodule.py
In https://nvbugspro.nvidia.com/bug/5060664 they notice a warning message about performance when pretraining with variable sequence lengths. This is largely an oversight since our test scripts didn't set both minimum and maximum seq_lens. We should have the default if min_seq_length is omitted be to just pad to the maximum sequence length for performance reasons.
> [!NOTE] …
=> set min seq len by default

docs/docs/models/ESM-2/pre-training.md, docs/docs/user-guide/examples/bionemo-esm2/finetune.ipynb, sub-packages/bionemo-core/src/bionemo/core/data/resources/esm2.yaml, sub-packages/bionemo-esm2/tests/bionemo/esm2/model/finetune/test_finetune_regressor.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/model/finetune/test_finetune_token_classifier.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/scripts/test_finetune_esm2.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/scripts/test_infer_esm2.py
Fixes failing tests due to NGC resource files being moved around, and renames some of the ESM-2 resources to better delineate checkpoints we trained on our internal data from those converted from the original ESM-2 model weights.
=> hotfix for some failing python tests due to NGC files being moved around

Dockerfile
With NVIDIA/NeMo#11777, NVIDIA/NeMo#11858, and https://github.com/NVIDIA/Megatron-LM/commit/a26b93d48e7d902d7d76e7a113fda05398043e6c, we're now ready to remove the manual tensorstore install from bionemo.
=> bump nemo and remove manual tensorstore install

Dockerfile, sub-packages/bionemo-esm2/tests/bionemo/esm2/model/test_model.py
The newer versions of the pytorch base image have up-to-date Apex and TransformerEngine libraries, we may no longer need to be re-building these from source.
=> remove the apex and TE build steps from our docker container

sub-packages/bionemo-core/src/bionemo/core/data/resources/esm2.yaml, sub-packages/bionemo-esm2/src/bionemo/esm2/model/convert.py, sub-packages/bionemo-esm2/src/bionemo/esm2/testing/__init__.py, sub-packages/bionemo-esm2/src/bionemo/esm2/testing/compare.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/model/test_convert.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/model/test_model.py, sub-packages/bionemo-llm/src/bionemo/llm/model/config.py, sub-packages/bionemo-testing/src/bionemo/testing/megatron_parallel_state_utils.py
Adds a conversion script to convert from huggingface to ESM-2 checkpoints
=> ESM-2 to NeMo checkpoint conversion

sub-packages/bionemo-core/src/bionemo/core/data/load.py, sub-packages/bionemo-core/tests/bionemo/core/data/test_load.py
Should fix issues like https://nvbugspro.nvidia.com/bug/5063178, where the SLURM environment picks up a stray and incorrect NGC api key.
=> catch ngc api key validation errors and default to not using an api key

.devcontainer/devcontainer.json, .devcontainer/initializeCommand.sh
Adds a short startup script to ensure opening the devcontainer doesn't crash because of a missing .ngc, .aws, or .netrc folder/file.
=> short script to initialize environment for devcontainer

.github/workflows/unit-tests.yml
Don't upload code coverage results from merge queue pipelines. See https://github.com/matplotlib/napari-matplotlib#155
=> Don't upload merge queue results to codecov

requirements-test.txt
Transformer engine seems to be having an issue with triton 3.2.0, pinning to 3.1.0 until we update to a new NGC base image
=> Pin triton version to avoid import error

.devcontainer/initializeCommand.sh
If this script exits unsuccessfully, the devcontainer launch stops. This makes sure that we exit successfully regardless of the status of ~/.netrc
=> fix devcontainer initialize script

sub-packages/bionemo-geneformer/tests/bionemo/geneformer/scripts/test_train_geneformer.py
This is one remaining outlier in our current test suite that takes a long time to run (~3 minutes by itself). https://app.codecov.io/gh/NVIDIA/bionemo-framework/tests/main
With #634 we'll run these tests anyways during the merge queue step, but marking this as slow should speed up the coverage runs in PRs and post-merge
=> Mark geneformer test_pretrain_cli as slow

.github/workflows/approvals.yml
Rather than having a bunch of red 'X's on PRs that haven't gotten the required +2 review, we could have a conditional step that only runs when the required approvals are met. If we mark this as the required step in our branch rules it has the same effect, without cluttering our PR status with a bunch of failed status checks
=> edit to approval workflow to avoid marking a failed action

Dockerfile
Adds back the custom transformer engine install to avoid the import error on python debugging. https://nvidia.slack.com/archives/C074Z808N05/p1737753519355939
=> add back transformer engine install

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
Adding clearer instruction related to expected format of bionemo version input, ie to be a commit hash or version tag
- [x ]  Other (please describe): template update
- [INCLUDE_SLOW_TESTS](https://github.com/NVIDIA/bionemo-framework/blob/main/docs/docs/user-guide/contributing/contributing.md#include_slow_tests) - Execute tests labelled as slow in pytest for extensive …
=> update issue templates

Dockerfile
There's now a 25.01 release of the pytorch base image, so we should try updating.
=> Update pytorch base image

.github/workflows/gh-docs-deploy.yml, .github/workflows/unit-tests.yml
Runs the full unit test suite nightly to track CI failures
=> Add scheduled nightly tests on github CI

sub-packages/bionemo-esm2/src/bionemo/esm2/scripts/finetune_esm2.py, sub-packages/bionemo-esm2/src/bionemo/esm2/scripts/train_esm2.py
Previously metric logging is blocking model parallel. Disable instead of raising error.
=> disable metric when model parallel

sub-packages/bionemo-evo2/src/bionemo/evo2/data/fasta_dataset.py, sub-packages/bionemo-evo2/src/bionemo/evo2/run/predict.py, sub-packages/bionemo-evo2/tests/bionemo/evo2/data/test_fasta_dataset.py
Refactor out Fasta dataset class to its own file and add tests.
=> Refactor out fasta dataset, add tests for it

.github/workflows/unit-tests.yml
Should fix the scheduled nightly tests that are currently failing on the trufflehog scan step.
=> split trufflehog scan into two actions, run on entire repo on scheduled event

.github/workflows/trufflehog.yml, .github/workflows/unit-tests.yml
Trufflehog scans are failing on main due to some false positive secrets on stale branches. Updating to make this it's own action following https://trufflesecurity.com/blog/running-trufflehog-in-a-github-action
=> move trufflehog scan to new action

.github/workflows/trufflehog.yml
This is a required check, but isn't really needed and doesn't seem to work properly in a merge queue. Here we skip the scan if we're in a merge queue
=> Trigger and skip trufflehog scan in merge group

Dockerfile
Removes `zstandard` after installing NeMo to avoid issues like the following downloading large binary files with ngcsdk. 
https://nvbugspro.nvidia.com/bug/5149698
```
raise DecodeError(
urllib3.exceptions.DecodeError: ('Received response with content-encoding: zstd, but failed to decode it.', ZstdError('cannot use a decompressobj multiple times'))
...
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: zstd, but failed to decode it.', ZstdError('cannot use a decompressobj multiple times'))
```
=> remove zstandard to address nvbug 5149698

sub-packages/bionemo-evo2/src/bionemo/evo2/run/train.py, sub-packages/bionemo-evo2/tests/bionemo/evo2/run/test_train.py, sub-packages/bionemo-testing/src/bionemo/testing/testing_callbacks.py
See new option `--early-stop-on-step` which may be used in JET tests to stop on a specific step without impacting the LR curve by changing `--max-steps`
=> If desired, training can be stopped on a specific step without impacting the LR curve.

ci/scripts/run_pytest.sh, ci/scripts/utils.sh, internal/scripts/run_dev.sh, justfile
Removes all traced of BIONEMO_HOME ENVVAR and the setup_bionemo_home script from our repository.
> [!NOTE]
> By default, the notebooks validation tests are skipped …
=> fix: removes BIONEMO_HOME from repository [JIRA-BIONEMO-482]

ci/scripts/build_docker_image.sh
THe commit from merge of https://github.com/NVIDIA/bionemo-framework/pull/742 introduced a change that broke docker building in CI. Hot fixing it
> [!NOTE]
> By …
=> hotfix: docker build in CI

sub-packages/bionemo-evo2/tests/bionemo/evo2/run/test_train.py
Marking as skip failing unit test for Evo2
```
sub-packages/bionemo-evo2/tests/bionemo/evo2/run/test_train.py::test_train_evo2_stops FAILED [ 79%]
.
.
.
11:44:55  /usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:385: in _save_topk_checkpoint
11:44:55      self._save_monitor_checkpoint(trainer, monitor_candidates)
11:44:55  /usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:705: in _save_monitor_checkpoint
11:44:55      self._update_best_and_save(current, trainer, monitor_candidates)
11:44:55  /usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:757: in _update_best_and_save
11:44:55      self._save_checkpoint(trainer, filepath)
11:44:55 …
```
=> hotfix CI:  failing test test_train_evo2_stops

Dockerfile
Reverting https://github.com/NVIDIA/bionemo-framework/commit/67a869b3c601096475b82c1da1d2339d860dbce1
> [!NOTE]
> By default, the notebooks validation tests are …
=> Revert commit 67a869b3c601096475b82c1da1d2339d860dbce1 (TE_VERSION=v1.13 fix)

Dockerfile
Removes llama-index from container to fix 2 HIGH and 1 CRIT CVE. We do not use this package and it's only used in nemo RAG here:
```
./3rdparty/NeMo/examples/nlp/rag/rag_generating.py:15:from llama_index.core import Settings, StorageContext, load_index_from_storage
./3rdparty/NeMo/examples/nlp/rag/rag_indexing.py:15:from llama_index.core import Settings, SimpleDirectoryReader, VectorStoreIndex
./3rdparty/NeMo/examples/nlp/rag/rag_indexing.py:16:from llama_index.core.node_parser import SentenceSplitter
./3rdparty/NeMo/nemo/collections/nlp/models/rag/custom_bert_embedder.py:19:from llama_index.core.bridge.pydantic import PrivateAttr
./3rdparty/NeMo/nemo/collections/nlp/models/rag/custom_bert_embedder.py:20:from llama_index.core.embeddings import BaseEmbedding …
```
=> Remove llama-index from container to fix CVEs

Dockerfile
ARM builds are still broken -- this should fix it. Just various dependency juggling. 
> [!NOTE]
> By default, the notebooks validation tests are skipped unless …
=> Fix ARM docker build

.github/.codecov.yml, .github/codecov.yml
Adds PR status checks for codecov.
See https://docs.codecov.com/docs/commit-status for more details on what this looks like
=> Add .codecov.yml status checks

sub-packages/bionemo-llm/src/bionemo/llm/data/datamodule.py
We don't need a backup apex import in bionemo-llm's datamodule, since we can be sure that import exists in our megatron version
=> Remove import guard in bionemo-llm

ci/benchmarks/partial-conv/esm2_pretrain.yaml, ci/benchmarks/partial-conv/evo2_pretrain.yaml, ci/benchmarks/partial-conv/geneformer_pretrain.yaml, ci/benchmarks/perf/esm2_pretrain.yaml, ci/benchmarks/perf/evo2_pretrain.yaml, ci/benchmarks/perf/geneformer_pretrain.yaml
Updating configs to adjust them to the recent changes in the CI
> [!NOTE]
We use …
=> updated configs for benchmarks

docs/requirements.txt
We added a number of temporary pins to our docs page to solve failures from pypi packages, but we can remove them now
=> Remove temporary pins in docs build

.github/workflows/unit-tests.yml, docs/docs/models/geneformer.md
Previously if pre-commit failed, it would cause `run-tests` to be skipped, which would then mean that `verify-tests-status` would give the PR the green light. That's obviously a problem, so we need to make sure all these tests are added to the verify-tests-status check. Ideally we could put some more logic in that if block to check if we're in a merge queue, whether tests were intentionally skipped, etc.
=> Add pre commit to verify test status

docs/docs/models/geneformer.md
=> fix geneformer image paths

docs/docs/models/geneformer.md
=> fix geneformer image links

sub-packages/bionemo-llm/src/bionemo/llm/utils/callbacks.py
Adds 'batch index' to the resulting prediction dictionary. this allows users to reconstruct the original ordering of predictions with multi-gpu inference. Prevents users from using 'epoch' mode of inference with multiple GPUs. this addresses a known issue: https://nvbugswb.nvidia.com/NvBugs5/SWBug.aspx?bugid=4717442&cmtNo=
- [x ] I have tested these changes locally
=> multi-gpu inference. Adds 'batch index' to the resulting prediction

Dockerfile
Pins ngcsdk since the download location for files seems to have changed in 3.64.4. See https://nvidia.slack.com/archives/C074Z808N05/p1746231345981209
=> pin ngcsdk

sub-packages/bionemo-evo2/src/bionemo/evo2/run/predict.py, sub-packages/bionemo-geneformer/src/bionemo/geneformer/model/finetune_token_regressor.py, sub-packages/bionemo-llm/src/bionemo/llm/model/loss.py, sub-packages/bionemo-llm/src/bionemo/llm/utils/megatron_utils.py
- https://github.com/NVIDIA/bionemo-framework/pull/798 (https://github.com/NVIDIA/bionemo-framework/pull/855) depends on a NeMo branch, which has been merged into NeMo `main`: https://github.com/NVIDIA/NeMo/pull/13436. Update to point to this trunk commit.
- NeMo ToT reverted the `cp_size` argument for `masked_token_loss` (https://github.com/NVIDIA/NeMo/pull/13295), so we do the CP reduction on our side now...
- Future Megatron bump will add the `* cp_size` multiplier to the loss, and break our inference unit tests due to `torch.inference_mode()` usage in Megatron.
=> Bump NeMo to use a trunk commit instead of a branch for Evo2 fixes and inference.

ci/scripts/run_pytest.sh, sub-packages/bionemo-evo2/tests/bionemo/evo2/run/test_train.py, sub-packages/bionemo-moco/src/bionemo/moco/testing/parallel_test_utils.py, sub-packages/bionemo-testing/src/bionemo/testing/megatron_parallel_state_utils.py
- Use a free port when instantiating the `MASTER_PORT` for the distributed environment.
- Unstage `sub-packages/bionemo-evo2/examples/fine-tuning-tutorial.ipynb` from `pytest`, due to an inclination of this notebook to leave behind a 32 GB orphaned GPU process.
- Blossom: https://prod.blsm.nvidia.com/bionemo-external-bionemo-fw/job/branch_pipeline/1216/
=> Fix CI issues on main branch.

sub-packages/bionemo-esm2/src/bionemo/esm2/scripts/infer_esm2.py
Add prediction_interval in call to infer_model in infer_esm2.py
Fixes https://nvbugspro.nvidia.com/bug/5289774
> [!NOTE]
> By default, the notebooks validation …
=> Add prediction_interval in call to infer_model in infer_esm2.py

sub-packages/bionemo-llm/src/bionemo/llm/lightning.py, sub-packages/bionemo-llm/tests/bionemo/llm/test_lightning.py
If the tensors passed to `batch_collator` are on different GPUs, they will now be consolidated onto one. The preferred GPU can be specified. Adds a multi-GPU test.
(cherry picked from commit ce7d2c422d28d354fb6658efb2752f81d7d3ee8b)
=> Fix bionemo.llm.lightning.batch_collator in multi-GPU case

docs/docs/assets/css/chatbot.css
To ensure the endpoints worked as intended in the live docs, the documentation chatbot was originally created with `display: none;` so that we could toggle it on/off. This MR sets it to be visible by default.
=> Turn on chatbot visibility by default

sub-packages/bionemo-esm2/examples/pretrain.md
Fix typo in example pretrain command
=> fix typo in pretrain.md

sub-packages/bionemo-esm2/src/bionemo/esm2/model/convert.py, sub-packages/bionemo-esm2/src/bionemo/esm2/testing/compare.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/model/test_convert.py, sub-packages/bionemo-llm/src/bionemo/llm/lightning.py
Adds the option to export ESM2 checkpoints to a huggingface-compatible format, and adds golden value tests to ensure we get the same outputs before and after round-tripping nemo.
=> Add esm2 checkpoint export

.devcontainer/devcontainer.json
These devcontainer fields didn't work in the first place and these images no longer exist
=> Remove cache-to and cache-from in devcontainer

ci/scripts/run_pytest.sh
Disables moco notebook which seems to have a flaky test.
> [!NOTE]
We use …
=> Disable moco notebook tests to fix CI

ci/benchmarks/partial-conv/esm2_pretrain.yaml
We still experience slight performance regression due to the recent NeMo & Megatron upgrade, but due to the fix in https://gitlab-master.nvidia.com/clara-discovery/bionemo/-/commit/971a640cb7b02c699fe17c6e4316aecaea4aa9fa the accuracy regression has been solved and the perf regression has been reduced. The 4h training still times out with 26500  so adjusting the number of iteration to execute the training in 4h
- [ x]  Other (please describe):
- [INCLUDE_NOTEBOOKS_TESTS](https://github.com/NVIDIA/bionemo-framework/blob/main/docs/docs/user-guide/contributing/contributing.md# …
=> Reduce number of training steps for partial-conv: esm2

sub-packages/bionemo-esm2/src/bionemo/esm2/scripts/train_esm2.py
Exposes the `weight_decay` parameter for ESM-2 training to the train_esm2 CLI. We need to change this to 0.1 for 15B training
=> expose esm-2 weight decay parameter

sub-packages/bionemo-evo2/tests/bionemo/evo2/run/test_train.py
This PR enables the `test_train_evo2_stops()` test.
> [!NOTE]
We use …
=> Fix test_train_evo2_stops test

ci/benchmarks/partial-conv/esm2_pretrain_recipes.yaml, ci/benchmarks/partial-conv/geneformer_pretrain.yaml
=> automated benchmarks: esm2 650M training analogous to bionemo-recipes

sub-packages/bionemo-evo2/tests/bionemo/evo2/run/test_train.py
Add fp8 stop and go test for evo2
> [!NOTE]
We use …
=> Add fp8 stop and go test for evo2

sub-packages/bionemo-esm2/src/bionemo/esm2/model/convert.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/model/test_convert.py
For some reason the previous way we determined the bionemo model's dtype wasn't working correctly for nv-trained checkpoint exports; here we use model.dtype directly. Adds a test for exporting the nvidia-trained ESM checkpoints.
=> change where dtype is found in checkpoint export

sub-packages/bionemo-esm2/src/bionemo/esm2/model/convert.py, sub-packages/bionemo-esm2/tests/bionemo/esm2/model/test_convert.py
Previously this weight was not initialized, and would be the result of whatever torch.empty() assigned to these values. If we want to use this layer in downstream tasks, we should at least randomly init these weights to reasonable values.
=> Reset parameters for the ESM-2 contact head on HF export

sub-packages/bionemo-esm2/examples/finetune.ipynb
update the esm2 finetuning tutorial 
> [!NOTE]
We use …
=> fix esm2 finetuning tutorial

sub-packages/bionemo-evo2/src/bionemo/evo2/run/train.py
Switch to megatron's more robust `calculate_per_token_loss=True` by default, and better masking procedure in NeMo that will be less likely to mask entire sequences.
Relates to https://github.com/NVIDIA/bionemo-framework/issues/1007 and depends on https://github.com/NVIDIA/NeMo/pull/14359
=> Better masking in evo2, and default use of more robust megatron loss

sub-packages/bionemo-scspeedtest/pyproject.toml
This pins a newer setuptools version in pyproject.toml to a newer version that is necessary for an editable install of this package.
=> updating setup tools in pyproject.toml of scspeedtest

.github/pull_request_template.md, .github/workflows/unit-tests.yml, .mdformat.toml, .pre-commit-config.yaml, README.md, docs/docs/index.md, docs/docs/main/about/background/megatron_datasets.md, docs/docs/main/about/releasenotes-fw.md, docs/docs/main/contributing/code-review.md, docs/docs/main/contributing/contributing.md, docs/docs/main/datasets/uniprot.md, docs/docs/main/getting-started/initialization-guide.md, docs/docs/main/getting-started/training-models.md, docs/docs/models/ESM-2/index.md, docs/docs/models/amplify.md, docs/docs/models/evo2.md, docs/docs/models/geneformer.md, sub-packages/bionemo-core/src/bionemo/core/data/README.md, sub-packages/bionemo-esm2/examples/pretrain.md, sub-packages/bionemo-example_model/README.md, sub-packages/bionemo-moco/blog.md, sub-packages/bionemo-moco/documentation.md, sub-packages/bionemo-scdl/README.md, sub-packages/bionemo-size-aware-batching/README.md, sub-packages/bionemo-webdatamodule/README.md
Reverts formatting to index.md and adds this page to mdformat's exclude list
=> revert formatting of docs page

.github/workflows/unit-tests-framework.yml
Hotfix to make sure that framework runs tests nightly. They didn't run last night: https://github.com/NVIDIA/bionemo-framework/actions/runs/17119727799
=> make sure framework ci runs on schedule events

Dockerfile
Removes deprecated internal tools from release image
=> remove ./internal copy in Dockerfile

sub-packages/bionemo-evo2/src/bionemo/evo2/run/predict.py
=> enable per output token likelihood prediction for evo2

.mdformat.toml, .pre-commit-config.yaml, docs/docs/index.md
The cards in the docs `index.md` require a specific format.
However, `mdformat` changes this format. To workaround this, we had to add excludes functionalty for `mdformat` that prevented it from formatting `index.md`. For some reason, the excludes functionality in `mdformat` which requires python 3.13. This is broke our nightly build.
To fix this, I've converted the `index.md` card logic from markdown to html, so that it no longer gets formatted. This removes the need for the excludes functionality and  the 3.13 dependency it brings.
=> Remove index.md markdown to prevent 3.13 requirement

.github/workflows/unit-tests-recipes.yml
This step will fail if we're not on a pull request branch; causing the schedule CI to fail
=> skip get-pr-info if we're not on a pull request branch

Dockerfile
- Add emacs-nox to image for developer velocity.  It very helpful to have a command-line editor built-into the container for quick investigation.
> [!NOTE]
> By …
=> add emacs-nox [bnm2717]
